name: build-script

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
    - uses: actions/setup-node@v4.0.0
      with:
         node-version: '16.x'
         cache: 'yarn'
    - name: use yarn
      run: |
       yarn install
       yarn build